# Generated by Django 5.0.4 on 2024-04-06 16:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('referral_code', models.CharField(blank=True, max_length=20, null=True)),
                ('registration_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('referral_points', models.IntegerField(default=0)),
            ],
        ),
    ]
