# Generated by Django 5.0.4 on 2024-04-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referralapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='myreferral_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
